### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by ghost** [xexpanderx/conky-drawer-interactive#1]
Since i am a newbie in linux i wanted to use your project on ubuntu 20.04 but unable because don't know how to use it.so please guide me in this regard.

**Comment by xexpanderx** [comment]
What have you tried so far?

**Comment by ghost** [comment]
I have installed the dependencies and followed the procedure but it gave me infinite list of errors... :disappointed:

**Comment by xexpanderx** [comment]
Can you paste all those errors here?

**Comment by ghost** [comment]
currently I'm not on my home machine 
but will post as soon as possible.

**Comment by xexpanderx** [comment]
Did you create a colorscheme with pywal? Did you also install dependencies for pywal (sudo apt install imagemagick).

I just tested it on Ubuntu 20.04 in a VM and it works fine.

**Comment by ghost** [comment]
Yes I installed all the dependencies.
But not created a colorscheme with pywal.
Well how to do that?

**Comment by xexpanderx** [comment]
Well, run this in a terminal:

`wal -i PATH_TO_YOUR_WALLPAPER`

Your wallpaper can be any JPG, PNG e.t.c.

**Comment by ghost** [comment]
okay thanks :heart:

**Comment by xexpanderx** [comment]
You're welcome.
