### ISSUE TITLE
Something wrong. Not running.

### ISSUE THREAD

**Issue by Kronosblaster** [xexpanderx/conky-drawer-interactive#2]
I keep running into this. It looks amazing but can't run it.
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value

**Comment by xexpanderx** [comment]
Can you change this line (line 431):

`local ok, err = pcall(function () draw_widgets(cr) end)`

to this

`draw_widgets(cr)`

and then re-run it and parse the output here please.

**Comment by Kronosblaster** [comment]
conky: llua_load: /home/dave/.conky/conky-drawer-interactive/lua/drawer.lua:10: unfinished string near '"'
conky: desktop window (1c0000f) is subwindow of root window (175)
conky: window type - normal
conky: drawing to created window (0x6a00002)
conky: drawing to double buffer
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value
conky: llua_do_call: function conky_start_widgets execution failed: attempt to call a nil value

**Comment by xexpanderx** [comment]
Hey, you don't have "pywal" installed, which is a required dependency. The script is picking up colors from your ~.cache/wal location. Because that does not exist, it will fail.

Please install pywal (https://github.com/dylanaraps/pywal), and generate some color-schemes with wal. Let me know if that fixed the problem for you.

**Comment by Kronosblaster** [comment]
I already have it installed
Requirement already satisfied: pywal in /usr/lib/python3.8/site-packages (3.3.0)

**Comment by xexpanderx** [comment]
Ok, can you please show me the content of your drawer.lua at /home/dave/.conky/conky-drawer-interactive/lua/?

**Comment by Kronosblaster** [comment]
require 'cairo'

function hex2rgb(hex)
	hex = hex:gsub("#","")
	return (tonumber("0x"..hex:sub(1,2))/255), (tonumber("0x"..hex:sub(3,4))/255), tonumber(("0x"..hex:sub(5,6))/255)
end

-- HTML colors
black="#000000"
"
function fix_text(text)
	if string.len(text) == 1 then
		new_text = "0" .. text .. "%"
		return new_text
	else
		new_text = text .. "%"
		return new_text
	end
end

function draw_background(cr, w, h)
    cairo_set_line_cap (cr, CAIRO_LINE_CAP_ROUND)
    --Top
	cairo_set_source_rgba(cr, r0, g0, b0, t0_top)
	cairo_arc(cr,w-(w-32),24,24,90*math.pi/180,270*math.pi/180)
	cairo_rel_line_to(cr,w-28,0)
	cairo_arc(cr,w-32,24,24,270*math.pi/180,90*math.pi/180)
	cairo_close_path(cr)
    cairo_fill(cr)
    --Top border
    cairo_set_operator(cr,CAIRO_OPERATOR_SOURCE)
    cairo_set_source_rgba(cr, r, g, b, t_top_border)
	cairo_arc(cr,w-(w-32),24,24,90*math.pi/180,270*math.pi/180)
	cairo_rel_line_to(cr,w-28,0)
	cairo_arc(cr,w-32,24,24,270*math.pi/180,90*math.pi/180)
	cairo_close_path(cr)
    cairo_stroke(cr)
    --Top hole
    cairo_set_source_rgba(cr, r, g, b, t_top_hole)
    cairo_set_line_width(cr, 4)
    cairo_move_to(cr,w-(w-32),24)
    cairo_rel_line_to(cr,w-64,0)
    cairo_stroke(cr)
    --Drawer
    drawer_width=38
    drawer_height=164
    cairo_set_operator(cr,CAIRO_OPERATOR_OVER)
    cairo_set_line_width(cr, 2)
    cairo_set_source_rgba(cr, r0, g0, b0, t0_drawer)
    cairo_move_to(cr,w-(w-drawer_width),24)
    cairo_rel_line_to(cr,0,h-drawer_height)
    z=-1
    for i=0, ((w-64)-12)/4 do
		cairo_rel_line_to(cr,4,4*z)
		z = z * -1
    end
    cairo_rel_line_to(cr,0,-(h-drawer_height))
    cairo_close_path(cr)
    cairo_fill(cr)
    --Drawer border
    cairo_set_line_width(cr, 2)
    cairo_set_source_rgba(cr, r, g, b, t0_drawer_border)
    cairo_move_to(cr,w-(w-drawer_width),24)
    cairo_rel_line_to(cr,0,h-drawer_height)
    z=-1
    for i=0, ((w-64)-12)/4 do
		cairo_rel_line_to(cr,4,4*z)
		z = z * -1
    end
    cairo_rel_line_to(cr,0,-(h-drawer_height))
    cairo_close_path(cr)
    cairo_stroke(cr)
    --Clock
    cairo_select_font_face (cr, "Dejavu Sans Book", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL)
    cairo_set_source_rgba(cr, r7, g7, b7, t7)
	cairo_set_font_size(cr, 24)
	ct = cairo_text_extents_t:create()
	cairo_text_extents(cr,conky_parse('${exec date +%H:%M}'),ct)
	cairo_move_to(cr,w-127,76)
	cairo_show_text(cr,conky_parse('${exec date +%H:%M}'))
	--Date
	cairo_set_font_size(cr, 16)
	ct = cairo_text_extents_t:create()
	cairo_text_extents(cr,conky_parse('${exec date +"%A - %d %B"}'),ct)
	cairo_move_to(cr,60,102)
	cairo_show_text(cr,conky_parse('${exec date +"%A - %d %B"}'))
	--Uptime
	uptime = conky_parse('${uptime}')
	cairo_set_font_size(cr, 12)
	ct = cairo_text_extents_t:create()
	cairo_text_extents(cr,"Uptime: " .. uptime,ct)
	cairo_move_to(cr,60,130)
	cairo_show_text(cr,"Uptime: " .. uptime)
	--CPU
	----Border
	cpu_x = 70
	cpu_y = 180
	cpu_move = 30
	cairo_set_source_rgba(cr, r1, g1, b1, t1)
    cairo_set_line_width(cr, 2)
    cairo_move_to(cr,cpu_x ,cpu_y)
	cairo_rel_line_to(cr,cpu_move,0)
	cairo_rel_line_to(cr,0,cpu_move)
	cairo_rel_line_to(cr,-cpu_move,0)
	cairo_set_line_join (cr, CAIRO_LINE_JOIN_ROUND);
    cairo_close_path(cr)
    cairo_stroke(cr)
    ----CPU hole
	cairo_arc(cr,cpu_x+5,cpu_y+5,2,0*math.pi/180,360*math.pi/180)
    cairo_fill(cr)
    ----Top pins
	cairo_set_line_width(cr, 2)
	cairo_set_line_join (cr, CAIRO_LINE_JOIN_MITER)
    for i=0, 4 do
		cairo_move_to(cr,cpu_x+3+6*i,cpu_y-5)
		cairo_rel_line_to(cr,0,-5)
		cairo_close_path(cr)
		cairo_stroke(cr)
    end
    ----Left pins
    for i=0, 4 do
		cairo_move_to(cr,cpu_x-5,cpu_y+3+6*i)
		cairo_rel_line_to(cr,-5,0)
		cairo_close_path(cr)
		cairo_stroke(cr)
    end
    --Right pins
    for i=0, 4 do
		cairo_move_to(cr,cpu_x+cpu_move+10,cpu_y+3+6*i)
		cairo_rel_line_to(cr,-5,0)
		cairo_close_path(cr)
		cairo_stroke(cr)
    end
    --Bottom pins
    for i=0, 4 do
		cairo_move_to(cr,cpu_x+3+6*i,cpu_y+cpu_move+10)
		cairo_rel_line_to(cr,0,-5)
		cairo_close_path(cr)
		cairo_stroke(cr)
    end
    for i=0, 10 do
    cairo_set_source_rgba(cr, r7, g7, b7, t7_indicator)
    cairo_arc(cr,cpu_x+cpu_move/2+47+20*i,cpu_y+cpu_move/2,6,0*math.pi/180,360*math.pi/180)
    cairo_fill(cr)
    end
    cpu_used = math.floor(10*tonumber(conky_parse("${cpu cpu0}"))/100)
    for i=0, cpu_used do
    cairo_set_source_rgba(cr, r1, g1, b1, t1)
    cairo_arc(cr,cpu_x+cpu_move/2+47+20*i,cpu_y+cpu_move/2,6,0*math.pi/180,360*math.pi/180)
    cairo_fill(cr)
    end
    --RAM structure
    cairo_set_source_rgba(cr, r2, g2, b2, t2)
    ram_x = 70
	ram_y = 240
	ram_move = 10
	cairo_move_to(cr,ram_x,ram_y)
	cairo_rel_line_to(cr,ram_move,0)
	cairo_rel_line_to(cr,-ram_move,0)
	cairo_rel_line_to(cr,0,48)
    cairo_stroke(cr)
    ----Right-circle
    cairo_arc(cr, ram_x+ram_move+5, ram_y, 4, 0*math.pi/180,180*math.pi/180)
    cairo_stroke(cr)
    --RAM structure 2
    cairo_move_to(cr,ram_x+ram_move+10,ram_y)
    cairo_rel_line_to(cr,10,0)
    cairo_rel_line_to(cr,0,10)
    cairo_rel_line_to(cr,-5,0)
    cairo_stroke(cr)
    ----Bottom-circle
    cairo_arc(cr, ram_x+ram_move+14, ram_y+14, 4, 90*math.pi/180,270*math.pi/180)
    cairo_stroke(cr)
     --RAM structure 3
    cairo_move_to(cr,ram_x+ram_move+15, ram_y+18)
    cairo_rel_line_to(cr,5,0)
    cairo_rel_line_to(cr,0,30)
    cairo_rel_line_to(cr,-11,0)
    cairo_stroke(cr)
    ----Left-circle
    cairo_arc(cr,ram_x+ram_move+5, ram_y+47, 4, 180*math.pi/180,0*math.pi/180)
    cairo_stroke(cr)
    --RAM structure 4 
    cairo_move_to(cr,ram_x+ram_move+1,ram_y+48)
    cairo_rel_line_to(cr,-10,0)
    cairo_stroke(cr)
    ----Pins-left
    for i=1, 4 do
		cairo_move_to(cr,ram_x+ram_move+18,ram_y+18+5*i)
		cairo_rel_line_to(cr,-4,0)
		cairo_stroke(cr)
    end
     ----Pins-right
	cairo_move_to(cr,ram_x+ram_move+18,ram_y+5)
	cairo_rel_line_to(cr,-4,0)
	cairo_stroke(cr)
    ----Left-squares
    cairo_rectangle (cr, ram_x+4, ram_y+35, 8,4);
    cairo_fill(cr)
    cairo_rectangle (cr, ram_x+4, ram_y+29, 8,4);
    cairo_fill(cr)  
    ----Right-squares
    cairo_rectangle (cr, ram_x+4, ram_y+8, 8, 4);
    cairo_fill(cr)
    cairo_rectangle (cr, ram_x+4, ram_y+14, 8, 4);
    cairo_fill(cr)
    for i=0, 10 do
    cairo_set_source_rgba(cr, r7, g7, b7, t7_indicator)
    cairo_arc(cr,ram_x+ram_move/2+57+20*i,ram_y+ram_move/2+19,6,0*math.pi/180,360*math.pi/180)
    cairo_fill(cr)
    end
    mem_used = math.floor(10*tonumber(conky_parse("${memperc}"))/100)
    for i=0, mem_used do
    cairo_set_source_rgba(cr, r2, g2, b2, t2)
    cairo_arc(cr,ram_x+ram_move/2+57+20*i,ram_y+ram_move/2+19,6,0*math.pi/180,360*math.pi/180)
    cairo_fill(cr)
    end
    --HDD
    hdd_x = 74
	hdd_y = 324
	hdd_move = 10
    cairo_set_source_rgba(cr, r3, g3, b3, t3)
	cairo_set_line_width(cr, 2)
	cairo_arc(cr, hdd_x-6, hdd_y-11,4,180*math.pi/180,270*math.pi/180)
	cairo_arc(cr,hdd_x+28, hdd_y-11,4,270*math.pi/180,360*math.pi/180)
	cairo_arc(cr, hdd_x+28, hdd_y+29,4,0*math.pi/180,90*math.pi/180)
	cairo_rel_line_to(cr,-9,0)
	cairo_rel_line_to(cr,0,-10)
	cairo_rel_line_to(cr,-16,0)
	cairo_rel_line_to(cr,0,10)
	cairo_rel_line_to(cr,-9,0)
	cairo_arc(cr, hdd_x-6, hdd_y+29,4,90*math.pi/180,180*math.pi/180)
	cairo_close_path(cr)
	cairo_stroke(cr)
	----Holes
	cairo_arc(cr,hdd_x-5,hdd_y+28,2,0*math.pi/180,360*math.pi/180)
	cairo_arc(cr,hdd_x+27,hdd_y+28,2,0*math.pi/180,360*math.pi/180)
	cairo_fill(cr)
	cairo_arc(cr,hdd_x-5,hdd_y-10,2,0*math.pi/180,360*math.pi/180)
	cairo_arc(cr,hdd_x+27,hdd_y-10,2,0*math.pi/180,360*math.pi/180)
	cairo_fill(cr)
	---Rectangle
	cairo_set_line_width(cr, 1)
	cairo_arc(cr,hdd_x-3.5,hdd_y+2.5,2,180*math.pi/180,270*math.pi/180)
	cairo_arc(cr,hdd_x+25.5,hdd_y+2.5,2,270*math.pi/180,0*math.pi/180)
	cairo_arc(cr,hdd_x+25.5,hdd_y+14.5,2,0*math.pi/180,90*math.pi/180)
	cairo_arc(cr,hdd_x-3.5,hdd_y+14.5,2,90*math.pi/180,180*math.pi/180)
	cairo_close_path(cr)
	cairo_stroke(cr)
	----HDD pins
	cairo_set_line_width(cr, 1)
	for i=0, 2 do
		cairo_rectangle (cr,hdd_x+6.5+4*i,hdd_y+26.5, 1, 7);
		cairo_stroke(cr)
    end
	--Pathname
	cairo_set_font_size(cr, 9)
	cairo_set_source_rgba(cr, r8, g8, b8, t8)
	ct = cairo_text_extents_t:create()
	cairo_text_extents(cr,"Root",ct)
    cairo_move_to(cr,hdd_x+11-ct.width/2,hdd_y+8+ct.height/2)
    cairo_show_text(cr,"Root")
    ---Hdd indicator
    fs_used = math.floor(4*tonumber(conky_parse("${fs_used_perc " .. "/" .. "}"))/100)
    for i=0, 10 do
		cairo_set_source_rgba(cr, r7, g7, b7, t7_indicator)
		cairo_arc(cr,hdd_x+hdd_move/2+53+20*i,hdd_y+hdd_move/2+4,6,0*math.pi/180,360*math.pi/180)
		cairo_fill(cr)
    end
    for i=0, fs_used do
		cairo_set_source_rgba(cr, r3, g3, b3, t3)
		cairo_arc(cr,hdd_x+hdd_move/2+53+20*i,hdd_y+hdd_move/2+4,6,0*math.pi/180,360*math.pi/180)
		cairo_fill(cr)
    end
    --Battery
 	cairo_set_source_rgba(cr, r4, g4, b4, t4)
	cairo_set_line_width(cr, 2)
	--Battery structure
	bat_x = 69
	bat_y = 386
	bat_move = 9
	bat_move_y=4
	cairo_arc(cr,bat_x+26,bat_y+4,4,270*math.pi/180,0*math.pi/180)
	cairo_arc(cr,bat_x+26,bat_y+36,4,0*math.pi/180,90*math.pi/180)
	cairo_arc(cr,bat_x+6,bat_y+36,4,90*math.pi/180,180*math.pi/180)
	cairo_arc(cr,bat_x+6,bat_y+4,4,180*math.pi/180,270*math.pi/180)
	cairo_close_path(cr)
	cairo_stroke(cr)
	----Top
	cairo_set_line_width(cr, 2)
	cairo_move_to(cr,bat_x+bat_move-5+6,bat_y-bat_move_y)
	cairo_rel_line_to(cr,0,5)
	cairo_arc(cr,bat_x+bat_move+5,bat_y-bat_move_y,4,180*math.pi/180,270*math.pi/180)
	cairo_rel_line_to(cr,6,0)
	cairo_arc(cr,bat_x+bat_move+9,bat_y-bat_move_y,4,270*math.pi/180,0*math.pi/180)
	cairo_rel_line_to(cr,0,4)
	cairo_stroke(cr)
	--Indicators
	battery_status = conky_parse("${battery_short}")
	battery_status = string.sub(battery_status,1,1)
    battery_percentage = math.floor(10*tonumber(conky_parse("${battery_percent}"))/100)
    for i=0, 10 do
    cairo_set_source_rgba(cr, r7, g7, b7, t7_indicator)
    cairo_arc(cr,bat_x+bat_move/2+59+20*i,bat_y+bat_move/2+12,6,0*math.pi/180,360*math.pi/180)
    cairo_fill(cr)
    end
    for i=0, battery_percentage do
    cairo_set_source_rgba(cr, r4, g4, b4, t4)
    cairo_arc(cr,bat_x+bat_move/2+59+20*i,bat_y+bat_move/2+12,6,0*math.pi/180,360*math.pi/180)
    cairo_fill(cr)
    end
    
	if battery_status == "C" or battery_status == "F" then
	    cairo_set_source_rgba(cr, r4, g4, b4, t4)
		cairo_set_line_width(cr, 1)
		cairo_move_to (cr, bat_x+11, bat_y+13)
		cairo_rel_line_to(cr,10,0)
		cairo_stroke(cr)
		cairo_move_to (cr, bat_x+16, bat_y+12)
		cairo_rel_line_to(cr,0,-4)
		cairo_stroke(cr)
		cairo_move_to (cr, bat_x+16, bat_y+14)
		cairo_rel_line_to(cr,0,4)
		cairo_stroke(cr)
		cairo_move_to (cr, bat_x+11, bat_y+32)
		cairo_rel_line_to(cr,10,0)
		cairo_stroke(cr)
		
	elseif battery_status == "D" then
		cairo_set_source_rgba(cr, r8, g8, b8, t8)
		cairo_set_line_width(cr, 2)
		cairo_move_to (cr, bat_x+11, bat_y+13)
		cairo_rel_line_to(cr,10,0)
		cairo_stroke(cr)
		cairo_move_to (cr, bat_x+16, bat_y+12)
		cairo_rel_line_to(cr,0,-4)
		cairo_stroke(cr)
		cairo_move_to (cr, bat_x+16, bat_y+14)
		cairo_rel_line_to(cr,0,4)
		cairo_stroke(cr)
		cairo_move_to (cr, bat_x+11, bat_y+32)
		cairo_rel_line_to(cr,10,0)
		cairo_stroke(cr)
	else
		cairo_set_source_rgba(cr, r8, g8, b8, t8)
		ct = cairo_text_extents_t:create()
		cairo_text_extents(cr,battery_status,ct)
		cairo_move_to(cr,bat_x+16-ct.width/2,bat_y+ct.height/2+20)
		cairo_show_text(cr,battery_status)
	end
end


function draw_widgets(cr)
	local w,h=conky_window.width,conky_window.height
	cairo_select_font_face (cr, "Dejavu Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL)
	cairo_set_font_size(cr, 12)
	r0, g0, b0 = hex2rgb(color0)
	r1, g1, b1 = hex2rgb(color1)
	r2, g2, b2 = hex2rgb(color2)
	r3, g3, b3 = hex2rgb(color3)
	r4, g4, b4 = hex2rgb(color4)
	r5, g5, b5 = hex2rgb(color5)
	r6, g6, b6 = hex2rgb(color6)
	r7, g7, b7 = hex2rgb(color7)
	r8, g8, b8 = hex2rgb(color8)
	r, g, b = hex2rgb(black)
	--Get coordinates of conky window and mouse
	x=tonumber(conky_parse("${exec xdotool search --name conky-drawer | sed -n 1p | xargs xdotool getwindowgeometry --shell | grep 'X' | tr -d 'X='}"))
	x_max = x+w
	y=tonumber(conky_parse("${exec xdotool search --name conky-drawer | sed -n 1p | xargs xdotool getwindowgeometry --shell | grep 'Y' | tr -d 'Y='}"))
	y_max = y+48
	mouse_x = tonumber(conky_parse("${exec xdotool getmouselocation --shell | grep 'X' | tr -d 'X='}"))
	mouse_y = tonumber(conky_parse("${exec xdotool getmouselocation --shell | grep 'Y' | tr -d 'Y='}"))
	--Draw background
	if mouse_x > x and mouse_x < x_max and mouse_y > y and mouse_y < y_max then
		t0_top=0.0
		t_top_border=0.0
		t_top_hole=0.5
		t0_drawer=1
		t0_drawer_border=0.2
		t1=1
		t2=1
		t3=1
		t4=1
		t5=1
		t6=1
		t7=1
		t7_indicator=0.2
		t8=1
	else
		t0_top=0.0
		t0_drawer=0
		t0_drawer_border=0.0
		t1=0
		t2=0
		t3=0
		t4=0
		t5=0
		t6=0
		t7=0
		t7_indicator=0.0
		t8=0
		t_top_border=0.0
		t_top_hole=0.2
	end
	draw_background(cr, w, h)
end

function conky_start_widgets()

	if conky_window==nil then return end
	local cs=cairo_xlib_surface_create(conky_window.display,conky_window.drawable,conky_window.visual, conky_window.width,conky_window.height)
	local cr=cairo_create(cs)	
	local ok, err = pcall(function () draw_widgets(cr) end)
	cairo_surface_destroy(cs)
	cairo_destroy(cr)
end

**Comment by xexpanderx** [comment]
Yes, it seems you have not set any pywal colorscheme yet. Please run this as an example in your terminal:

`wal --theme dkeg-simplicity`

and then run the `start_conky.sh` again.

**Comment by Kronosblaster** [comment]
conky: desktop window (1e0000f) is subwindow of root window (175)
conky: window type - normal
conky: drawing to created window (0x5c00002)
conky: drawing to double buffer
conky: Lua script '/home/dave/.conky/conky-drawer-interactive/lua/drawer.lua' reloaded
conky: can't open /sys/class/power_supply/BAT0/uevent: No such file or directory
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
conky: can't open /proc/apm: No such file or directory
conky: can't open /sys/class/power_supply/BAT0/uevent: No such file or directory
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x10981e9
  Serial number of failed request:  771
  Current serial number in output stream:  771
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x10984b2
  Serial number of failed request:  1515
  Current serial number in output stream:  1515
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x10984d0
  Serial number of failed request:  726
  Current serial number in output stream:  726
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x10984d0
  Serial number of failed request:  726
  Current serial number in output stream:  726
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x10984d0
  Serial number of failed request:  1515
  Current serial number in output stream:  1515
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x109855f
  Serial number of failed request:  726
  Current serial number in output stream:  726
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x1098599
  Serial number of failed request:  1517
  Current serial number in output stream:  1517
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1097468
  Serial number of failed request:  24
  Current serial number in output stream:  24
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1097469
  Serial number of failed request:  31
  Current serial number in output stream:  31
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1098599
  Serial number of failed request:  726
  Current serial number in output stream:  726
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x116a402
  Serial number of failed request:  1426
  Current serial number in output stream:  1426
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x2a00047
  Serial number of failed request:  91
  Current serial number in output stream:  91
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x6c0005a
  Serial number of failed request:  389
  Current serial number in output stream:  389
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x6c0005a
  Serial number of failed request:  163
  Current serial number in output stream:  163
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x2a019df
  Serial number of failed request:  152
  Current serial number in output stream:  152
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x2a019df
  Serial number of failed request:  152
  Current serial number in output stream:  152
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x6c0022b
  Serial number of failed request:  230
  Current serial number in output stream:  230
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x6c00bbe
  Serial number of failed request:  244
  Current serial number in output stream:  244
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x6c00c1f
  Serial number of failed request:  421
  Current serial number in output stream:  421
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x6c00d1e
  Serial number of failed request:  419
  Current serial number in output stream:  419
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x6c00d1e
  Serial number of failed request:  419
  Current serial number in output stream:  419
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x6c00ef2
  Serial number of failed request:  179
  Current serial number in output stream:  179
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x6c00ef2
  Serial number of failed request:  179
  Current serial number in output stream:  179
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars) 
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
There are no windows in the stack
Invalid window '%1'
Usage: getwindowgeometry [window=%1] [--shell] [--prefix <STR>]
--shell      - output shell variables for use with eval
--prefix STR - use prefix for shell variables names (max 16 chars
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)

**Comment by Kronosblaster** [comment]
That helped. But still not working.

**Comment by Kronosblaster** [comment]
Thanks for the help. It works now.
